name: nodejs-expts-workflow

on:
  push:
    paths:
      - .github/workflows/node-expts.yaml
      - node_expts_blog-example/**

defaults:
  run:
    working-directory: "./node_expts_blog-example/"

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x 
      - name: Restore or save cache for dev Dependencies
        uses: actions/cache@v3
        env:
          cache-name: npm-node-modules-dev
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-dev 
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm run test